//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnFptShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesSlider
    {
        public int CategoriesSliderID { get; set; }
        public string CateSliderImage { get; set; }
        public Nullable<int> CateID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
