
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DuAnFptShop.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customer
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {

            this.Orders = new HashSet<Order>();

        }


        public int CusID { get; set; }

        public string CusName { get; set; }

        public string CusPhone { get; set; }

        public Nullable<bool> CusGender { get; set; }

        public string CusEmail { get; set; }

        public string CusPassword { get; set; }

        [NotMapped]
        [Compare("CusPassWord")]
        [DisplayName("Nhap lai mat khau")]

        public string ConfirmPass { get; set; }
        [NotMapped]

        public string ErrorLogin { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Order> Orders { get; set; }



    }

}
