
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DuAnFptShop.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProductDiscount
{

    public int DiscountID { get; set; }

    public Nullable<int> ProductDetailID { get; set; }

    public string DiscountType { get; set; }

    public Nullable<decimal> DiscountValue { get; set; }

    public string DiscountDecription { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }



    public virtual ProductDetail ProductDetail { get; set; }

}

}
