
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DuAnFptShop.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProductNew
{

    public int ProductNewsID { get; set; }

    public string NewsTitle { get; set; }

    public string NewsImage { get; set; }

    public string NewsTags { get; set; }

    public Nullable<int> ProductID { get; set; }

    public string TypeNews { get; set; }



    public virtual Product Product { get; set; }

}

}
